[flake8]
exclude = [
    ".git", 
    "__pycache__", 
    "tests/*"
]
max-line-length = 120
ignore="W293,W504"


[tool.pytest.ini_options]
testpaths = [
    "tests"
]
addopts = [
    "--cov=los_tools",
    "--cov-report=term-missing:skip-covered",
    "-rP",
    "-vv",
    "-s"
]

[tool.black]
line-length = 120

[tool.isort]
atomic = true
profile = "black"
line_length = 120
skip_gitignore = true

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = "W293,W504,E0611"

[tool.mypy]
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
no_pretty = true
no_strict_optional = true
