[flake8]
exclude = [
    ".git", 
    "__pycache__", 
    "tests/*"
]
max-line-length = 120
ignore="W293,W504"


[tool.pytest.ini_options]
testpaths = [
    "tests"
]
addopts = [
    "--cov=los_tools",
    "--cov-report=term-missing:skip-covered",
    "-rP",
    "-vv",
    "-s"
]
qgis_canvas_width=2000
qgis_canvas_height=2000

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "redefined-outer-name",
    "no-name-in-module",
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "invalid-name",
    "too-many-arguments",
    "attribute-defined-outside-init"
]

[tool.mypy]
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
no_pretty = true
no_strict_optional = true
