site_name: LoS Tools
site_url: https://jancaha.github.io/qgis_los_tools/
site_description: Plugin for QGIS providing tools to construct and analyse Lines-of-Sight

site_author: Jan Caha
copyright: Copyright &copy; 2020 <a href="https://twitter.com/cahik13">Jan Caha</a>.

repo_url: https://github.com/JanCaha/qgis_los_tools
edit_uri: ""

theme:
    name: cerulean
    custom_dir: custom_theme/

extra_css:
    - css\additions.css

extra_javascript:
    - //code.jquery.com/jquery-3.6.0.min.js

docs_dir: pages
site_dir: docs

plugins:
    - search
    - glightbox:
          touchNavigation: true
          loop: false
          effect: zoom
          slide_effect: slide
          width: 100%
          height: auto
          zoomable: true
          draggable: true
          skip_classes:
              - custom-skip-class-name
          auto_caption: false
          caption_position: bottom
          background: white
          shadow: true
          manual: false
