site_name: LoS Tools
site_url: https://jancaha.github.io/qgis_los_tools/
site_description: Plugin for QGIS providing tools to construct and analyse Lines-of-Sight

site_author: Jan Caha
copyright: Copyright &copy; 2020 <a href="https://twitter.com/cahik13">Jan Caha</a>.

repo_url: https://github.com/JanCaha/qgis_los_tools
edit_uri: ""

theme:
    name: cerulean
    custom_dir: custom_theme/
    
extra_css: [css\additions.css]

docs_dir: pages
site_dir: docs
    
plugins:
    - search