name: Test Docker

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    container: 
      image: qgis/qgis:latest
      options: -e DISPLAY=:99
      
    steps:
      - name: Checkout to directory
        run: git clone https://$REPO_ACCESS_TOKEN:x-oauth-basic@github.com/JanCaha/qgis_los_tools.git /tests_directory
                            
      - name: Setup plugin
        run: qgis_setup.sh los_tools  
      
      - name: Remove files from plugin folder
        run: rm -f  /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools
        
      - name: Copy everything to plugin folder
        run: ln -s /tests_directory/los_tools /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools
      
      - name: Install python requirements
        run: pip3 install -r /tests_directory/REQUIREMENTS_TESTING.txt
        
      - name: explore directory
        run: |
          cd /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools
          dir
          cd test
          dir
        
      - name: Run tests using test suite
        run: qgis_testrunner.sh los_tools.package_test_suite.test_package
