name: Tests for Plugin LoS Tools

on:
  push:
    paths:
    - "los_tools/**"
    - ".github/workflows/test_plugin.yaml"
    - "tests/**"

jobs:

  Tests-plugin-LoS-Tools:

    runs-on: ubuntu-latest

    container: cahik/vscode-ubuntu-qgis-testing:v2

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Python Path
        run: echo $PYTHONPATH

 
      - name: Run Tests
        run: |
          pytest tests --cov=los_tools --cov-report=term-missing:skip-covered -rP -s