name: Tests for Plugin

on:
  push:
    paths:
    - "los_tools/**"
    - ".github/workflows/test_plugin.yaml"

env:
  # plugin name/directory where the code for the plugin is stored
  PLUGIN_NAME: los_tools
  # the path to file that handles test running inside the github repository
  PATH_TO_TEST_RUNNER: los_tools/package_test_suite.py
  # Docker settings
  DOCKER_IMAGE: qgis/qgis
  DOCKER_IMAGE_TAG: latest

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker pull and create qgis-testing-environment
        run: |
          docker pull "$DOCKER_IMAGE":"$DOCKER_IMAGE_TAG"
          docker run -d --name qgis-testing-environment -v "$GITHUB_WORKSPACE":/tests_directory -e DISPLAY=:99 "$DOCKER_IMAGE":"$DOCKER_IMAGE_TAG"

      - name: Docker set up QGIS
        run: |
          docker exec qgis-testing-environment sh -c "qgis_setup.sh $PLUGIN_NAME"
          docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
          docker exec qgis-testing-environment sh -c "ln -s /tests_directory/$PLUGIN_NAME /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
          docker exec qgis-testing-environment sh -c "pip3 install -r /tests_directory/REQUIREMENTS_TESTING.txt"

      # tests dont run unless the tests_directory is in path
      # PYTHONPATH in docker cannot be edit so we have to construct it completely and run the tests with it
      # PYTHONPATH is from https://github.com/qgis/QGIS/blob/master/.docker/qgis.dockerfile
      - name: Docker run plugin tests
        env:
          PYTHON_PATH: PYTHONPATH=/tests_directory:/usr/share/qgis/python/:/usr/share/qgis/python/plugins:/usr/lib/python3/dist-packages/qgis:/usr/share/qgis/python/qgis
        run: |
          docker exec qgis-testing-environment sh -c "$PYTHON_PATH python3 /tests_directory/$PATH_TO_TEST_RUNNER"