name: Test plugin

on:
  push:
    paths:
    - "los_tools/**"
    - ".github/workflows/test_plugin.yaml"

jobs:
  my_job:
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: '/__w/qgis_los_tools/qgis_los_tools/'

      - name: print dir
        run: |
          cd /tests_directory/
          dir

      - run: |
          qgis_setup.sh /__w/qgis_los_tools/qgis_los_tools/los_tools
          rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools
          ln -s /__w/qgis_los_tools/qgis_los_tools/los_tools /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools
          pip3 install -r /tests_directory/REQUIREMENTS_TESTING.txt
          qgis_testrunner.sh los_tools.package_test_suite.test_package
