name: Test plugin

on:
  push:
    paths:
    - "los_tools/**"
    - ".github/workflows/test_plugin.yaml"

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: '/home/runner/work/qgis_los_tools/qgis_los_tools'

      - name: Docker
        run: |
          docker pull qgis/qgis:latest
          docker run -d --name qgis-testing-environment -v /home/runner/work/qgis_los_tools/qgis_los_tools:/tests_directory -e DISPLAY=:99 qgis/qgis:latest
          docker exec qgis-testing-environment sh -c "qgis_setup.sh los_tools"