name: Test plugin

on:
  push:
    paths:
    - "los_tools/**"
    - ".github/workflows/test_plugin.yaml"

jobs:
  my_job:
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          qgis_setup.sh los_tools
