name: Tests for Plugin LoS Tools

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "los_tools/**"
      - ".github/workflows/test_plugin.yaml"
      - "tests/**"

jobs:

  Tests-plugin-LoS-Tools:

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        qgis-version: [ "3.22", "3.28", "3.34", "3.40", "3.44" ]

    steps:

      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"
          skip_after_successful_duplicate: "true"

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          use-mamba: true
          channels: conda-forge,defaults

      - name: Create environment and install QGIS
        run: |
          conda create -n qgis_env --no-default-packages --yes
          conda install -n qgis_env qgis=${{ matrix.qgis-version }} pytest pytest-qt pytest-cov --yes
          conda run -n qgis_env pip install --no-cache-dir pytest-qgis

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Tests
        run: |
          conda run -n qgis_env pytest tests --cov=los_tools --cov-report=term-missing:skip-covered -rP -s
