name: Test plugin

on:
  push:
    paths:
    - "los_tools/**"
    - ".github/workflows/test_plugin.yaml"

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: '/home/runner/work/qgis_los_tools/qgis_los_tools'

      - name: Docker pull and create qgis-testing-environment
        run: |
          docker pull qgis/qgis:latest
          docker run -d --name qgis-testing-environment -v /home/runner/work/qgis_los_tools/qgis_los_tools:/tests_directory -e DISPLAY=:99 qgis/qgis:latest

      - name: Docker set up QGIS
        run: |
          docker exec qgis-testing-environment sh -c "qgis_setup.sh los_tools"
          docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools"
          docker exec qgis-testing-environment sh -c "ln -s /tests_directory/los_tools /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools"
          docker exec qgis-testing-environment sh -c "pip3 install -r /tests_directory/REQUIREMENTS_TESTING.txt"

      - name: Docker run plugin tests
        run: |
          docker exec qgis-testing-environment sh -c "export PYTHONPATH=$PYTHONPATH:/tests_directory/"
          docker exec qgis-testing-environment sh -c "PYTHONPATH=$PYTHONPATH:/tests_directory/:/usr/share/qgis/python/plugins/processing python3 -c 'import sys;print(sys.path)'"
          docker exec qgis-testing-environment sh -c "PYTHONPATH=$PYTHONPATH:/tests_directory/:/usr/share/qgis/python/plugins/processing python3 -m los_tools"
          docker exec qgis-testing-environment sh -c "python3 /tests_directory/los_tools/package_test_suite.py"