name: Test plugin

on:
  push:
    paths:
    - "los_tools/**"
    - ".github/workflows/test_plugin.yaml"

jobs:
  my_job:
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis
      options: -e DISPLAY=:99
      volumes:
        - /__w/qgis_los_tools/qgis_los_tools/:/tests_directory

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: '/__w/qgis_los_tools/qgis_los_tools/'

      - name: print dir
        run: |
          cd /__w/qgis_los_tools/qgis_los_tools/
          dir

      - name: copy
        run: |
          cp -r /__w/qgis_los_tools/qgis_los_tools/. /tests_directory/

      - name: print dir
        run: |
          cd /tests_directory
          dir
          
      - name: print env
        run: printenv

      - run: |
          qgis_setup.sh los_tools
          rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools
          ln -s /tests_directory/los_tools /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools
          pip3 install -r /tests_directory/REQUIREMENTS_TESTING.txt
          python3 /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/los_tools/package_test_suite.py
